const TYPES = {
    Logger: Symbol.for("Logger"),
    Database: Symbol.for("Database"),
    Server: Symbol.for("Server"),
    HTTPRouter: Symbol.for("HTTPRouter"),

    // Impelementation Domain Service
    UserRepository: Symbol.for("UserRepository"),
    RoleRepository: Symbol.for("RoleRepository"),
    AccessRepository: Symbol.for("AccessRepository"),
    PermissionRepository: Symbol.for("PermissionRepository"),
    AccessPermissionRepository: Symbol.for("AccessPermissionRepository"),

    ProblemRepository: Symbol.for("ProblemRepository"),
    DepectsRepository: Symbol.for("DepectsRepository"),
    ShiftsRepository: Symbol.for("ShiftsRepository"),
    MachineRepository: Symbol.for("MachineRepository"),
    LineRepository: Symbol.for("LineRepository"),
    MethodRepository: Symbol.for("MethodRepository"),
    PartRepository: Symbol.for("PartRepository"),
    EquipmentRepository: Symbol.for("EquipmentRepository"),
    MaterialRepository: Symbol.for("MaterialRepository"),
    PositionRepository: Symbol.for("PositionRepository"),
    ManpowerRepository: Symbol.for("ManpowerRepository"),
    SessionLoginRepository: Symbol.for("SessionLoginRepository"),
    TaskRepository: Symbol.for("TaskRepository"),
    ScheduleRepository: Symbol.for("ScheduleRepository"),
    ProductionOrderRepository: Symbol.for("ProductionOrderRepository"),
    ProductionEquipmentRepository: Symbol.for("ProductionEquipmentRepository"),
    ProductionManpowerRepository: Symbol.for("ProductionManpowerRepository"),
    ProductionProblemRepository: Symbol.for("ProductionProblemRepository"),
    ProductionDefectRepository: Symbol.for("ProductionDefectRepository"),
    PreparationTimeLogRepository: Symbol.for("PreparationTimeLogRepository"),
    MethodLogRepository: Symbol.for("MethodLogRepository"),
    ProductionMaterialRepository: Symbol.for("ProductionMaterialRepository"),
    MaterialChangedLogRepository: Symbol.for("MaterialChangedLogRepository"),

    // Service Layer
    UserService: Symbol.for("UserService"),
    WebadminAuthService: Symbol.for("WebadminAuthService"),
    RoleService: Symbol.for("RoleService"),
    AccessService: Symbol.for("AccessService"),

    ProblemServince: Symbol.for("ProblemServince"),
    DepectsService: Symbol.for("DepectsService"),
    ShiftsService: Symbol.for("ShiftsService"),
    MachineService: Symbol.for("MachineService"),
    LineService: Symbol.for("LineService"),
    MethodService: Symbol.for("MethodService"),
    PartService: Symbol.for("PartService"),
    EquipmentService: Symbol.for("EquipmentService"),

    PermissionService: Symbol.for("PermissionService"),
    MaterialService: Symbol.for("MaterialService"),
    PositionService: Symbol.for("PositionService"),
    ManpowerService: Symbol.for("ManpowerService"),
    hmiAuthService: Symbol.for("hmiAuthService"),
    sessionLoginService: Symbol.for("sessionLoginService"),
    ProductionPlanService: Symbol.for("ProductionPlanService"),
    ScheduleService: Symbol.for("ScheduleService"),
    MenuControlService: Symbol.for("MenuControlService"),
    PreparationService: Symbol.for("PreparationService"),
    ProductionProblemService: Symbol.for("ProductionProblemService"),
    ProductionDefectService: Symbol.for("ProductionDefectService"),
    MethodHmiService: Symbol.for("MethodHmiService"),
    ProductionSupportService: Symbol.for("ProductionSupportService"),
};

export { TYPES };
